apiVersion: v1
kind: ConfigMap
metadata:
  name: driver-service-config
  namespace: rideshare-data
data:
  REDIS_HOST: "teleios-daniel-dev-redis.tjh5n9.ng.0001.euw1.cache.amazonaws.com"
  REDIS_PORT: "6379"
  PORT: "3003"
  NODE_ENV: "production"
  FRONTEND_URL: "https://daniel-resume.xyz"
  JWT_EXPIRES_IN: "2d"
  EMAIL_SERVICE_URL: "http://email-service:3002"
  RIDER_SERVICE_URL: "http://rider-service:3001"
  TRIP_SERVICE_URL: "http://trip-service:3005"