apiVersion: v1
kind: ConfigMap
metadata:
  name: rider-service-config
  namespace: rideshare-data
data:
  NODE_ENV: "production"
  PORT: "3001"
  JWT_EXPIRES_IN: "7d"
  REDIS_HOST: "redis-cluster"
  REDIS_PORT: "6379"
  FRONTEND_URL: "https://daniel.teleioslabs.net"
  EMAIL_SERVICE_URL: "http://email-service"
  RIDER_SERVICE_URL: "http://rider-service"
  TRIP_SERVICE_URL: "http://trip-service"