apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-service-config
  namespace: rideshare-data
data:
  NEXT_PUBLIC_DRIVER_API: "https://daniel.teleioslabs.net/api/driver"
  NEXT_PUBLIC_RIDER_API: "https://daniel.teleioslabs.net/api/rider"
  NEXT_PUBLIC_TRIP_API: "https://daniel.teleioslabs.net/api/trip"
  NEXT_PUBLIC_MATCHING_API: "https://daniel.teleioslabs.net/api/matching"
  NEXT_PUBLIC_WS_URL: "wss://daniel.teleioslabs.net/api/matching"
  NODE_ENV: "production"
  PORT: "3000"