apiVersion: v1
kind: ConfigMap
metadata:
  name: trip-service-config
  namespace: rideshare-data
data:
  PORT: "3005"
  REDIS_TLS: "false"
  DEBUG: "False"
  ALLOWED_ORIGINS: "https://daniel.teleioslabs.net"