apiVersion: v1
kind: ConfigMap
metadata:
  name: trip-service-config
  namespace: rideshare-data
data:
  PORT: "3005"
  REDIS_TLS: "false"
  DEBUG: "False"
  ALLOWED_ORIGINS: "https://daniel-resume.xyz"
  REDIS_HOST: "teleios-daniel-dev-redis.tjh5n9.ng.0001.euw1.cache.amazonaws.com"
  REDIS_PORT: "6379"