# 1. The Trip Service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trip-service
  namespace: rideshare-data
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: trip-service
  template:
    metadata:
      labels:
        app: trip-service
    spec:
      containers:
        - name: trip-service
          image: 221693237976.dkr.ecr.eu-west-1.amazonaws.com/daniel-trip-service:v2
          ports:
            - containerPort: 3005 
          
          # configuration variables
          envFrom:
            - configMapRef:
                name: trip-service-config
          
          #  sensitive AWS database connections
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: rideshare-db-credentials
                  key: DATABASE_URL
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: rideshare-db-credentials
                  key: REDIS_URL
                  
          readinessProbe:
            httpGet:
              path: /health
              port: 3005
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 3005
            initialDelaySeconds: 30
            periodSeconds: 30
            failureThreshold: 3
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"

---
# 2. The Internal Network Service
apiVersion: v1
kind: Service
metadata:
  name: trip-service
  namespace: rideshare-data
spec:
  selector:
    app: trip-service
  ports:
    - protocol: TCP
      port: 3005
      targetPort: 3005