# ── secrets.tf ────────────────────────────────────────────────────
#
# Creates every AWS Secrets Manager secret the application needs.
# This runs as part of terraform apply — by the time the EKS cluster
# is up and the platform-setup workflow applies the ExternalSecret
# manifests, all secrets already exist and are fully populated.
#
# How the values are sourced:
#   - DATABASE_URL / REDIS_URL  → computed from RDS & Redis module outputs
#   - Passwords (Redis, JWT, replication) → generated by random_password
#   - External credentials (Azure, Google, Mapbox) → Terraform Cloud
#     sensitive variables (set in the workspace UI, never in tfvars)
#
# Secret naming matches the keys in rideshare-k8s/platform/secrets/external-secrets.yaml

# ── Generated passwords ───────────────────────────────────────────
# These are generated once and stored in Terraform state (encrypted
# in Terraform Cloud). They never need to be set manually.

resource "random_password" "redis" {
  length  = 32
  special = false # ElastiCache auth tokens disallow most special characters
}

resource "random_password" "postgres_repl" {
  length  = 24
  special = false
}

resource "random_password" "jwt_secret" {
  length  = 64
  special = false
}

# ── 1. daniel-database-url ────────────────────────────────────────
# Read by: all backend services (driver, rider, trip, matching)
# Contains the full RDS connection URL, Redis URL, and all passwords
# that the postgres StatefulSet and redis StatefulSet also need.
resource "aws_secretsmanager_secret" "database_url" {
  name                    = "${var.student_name}-database-url"
  description             = "RDS and Redis connection strings for all rideshare services"
  recovery_window_in_days = 0
  tags                    = var.tags
}

resource "aws_secretsmanager_secret_version" "database_url" {
  secret_id = aws_secretsmanager_secret.database_url.id

  # module.rds.db_endpoint already includes the port (hostname:5432)
  # module.redis.redis_endpoint is the hostname only — port 6379 added below
  secret_string = jsonencode({
    DATABASE_URL        = "postgresql://${var.rds_db_username}:${var.rds_db_password}@${module.rds.db_endpoint}/${var.rds_db_name}"
    DATABASE_READ_URL   = "postgresql://${var.rds_db_username}:${var.rds_db_password}@${module.rds.db_endpoint}/${var.rds_db_name}"
    REDIS_URL           = "redis://:${random_password.redis.result}@${module.redis.redis_endpoint}:6379"
    REDIS_HOST          = module.redis.redis_endpoint
    REDIS_PASSWORD      = random_password.redis.result
    POSTGRES_ADMIN_USER = var.rds_db_username
    POSTGRES_ADMIN_PASS = var.rds_db_password
    POSTGRES_REPL_USER  = "replicator"
    POSTGRES_REPL_PASS  = random_password.postgres_repl.result
  })

  depends_on = [module.rds, module.redis]
}

# ── 2. daniel-jwt-secret-driver-and-rider ─────────────────────────
# Read by: driver-service and rider-service for signing/verifying JWTs
resource "aws_secretsmanager_secret" "jwt_secret" {
  name                    = "${var.student_name}-jwt-secret-driver-and-rider"
  description             = "JWT signing secret for driver and rider authentication"
  recovery_window_in_days = 0
  tags                    = var.tags
}

resource "aws_secretsmanager_secret_version" "jwt_secret" {
  secret_id = aws_secretsmanager_secret.jwt_secret.id

  secret_string = jsonencode({
    JWT_SECRET = random_password.jwt_secret.result
  })
}

# ── 3. daniel-email-service ───────────────────────────────────────
# Read by: email-service (Python/Flask)
# Values come from Terraform Cloud sensitive variables — they are your
# Azure Communication Services credentials and cannot be generated.
resource "aws_secretsmanager_secret" "email_service" {
  name                    = "${var.student_name}-email-service"
  description             = "Azure Communication Services credentials for email-service"
  recovery_window_in_days = 0
  tags                    = var.tags
}

resource "aws_secretsmanager_secret_version" "email_service" {
  secret_id = aws_secretsmanager_secret.email_service.id

  secret_string = jsonencode({
    AZURE_EMAIL_CONNECTION_STRING = var.azure_email_connection_string
    SENDER_EMAIL                  = var.sender_email
  })
}

# ── 4. daniel-google-oauth ────────────────────────────────────────
# Read by: rider-service for Google OAuth sign-in
# Values come from Terraform Cloud sensitive variables.
resource "aws_secretsmanager_secret" "google_oauth" {
  name                    = "${var.student_name}-google-oauth"
  description             = "Google OAuth 2.0 client credentials"
  recovery_window_in_days = 0
  tags                    = var.tags
}

resource "aws_secretsmanager_secret_version" "google_oauth" {
  secret_id = aws_secretsmanager_secret.google_oauth.id

  secret_string = jsonencode({
    GOOGLE_CLIENT_ID     = var.google_client_id
    GOOGLE_CLIENT_SECRET = var.google_client_secret
  })
}

# ── 5. daniel-mapbox ──────────────────────────────────────────────
# Read by: frontend pod at runtime (separate from the build-time token
# baked into the Next.js bundle via NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN)
resource "aws_secretsmanager_secret" "mapbox" {
  name                    = "${var.student_name}-mapbox"
  description             = "Mapbox access token for frontend maps"
  recovery_window_in_days = 0
  tags                    = var.tags
}

resource "aws_secretsmanager_secret_version" "mapbox" {
  secret_id = aws_secretsmanager_secret.mapbox.id

  secret_string = jsonencode({
    NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN = var.mapbox_access_token
  })
}
