# 1. Application Connection URLs (For Rider, Driver, Trip services)
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rideshare-secrets-fetcher
  namespace: rideshare-data
spec:
  refreshInterval: "1h"
  secretStoreRef:
    # This points directly to the ClusterSecretStore we just made above
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    # This is the name of the local Kubernetes Secret it will generate
    name: rideshare-db-credentials 
    creationPolicy: Owner
  data:
    # 1. Fetching the Primary Database URL (For Writes)
    - secretKey: DATABASE_URL
      remoteRef:
        key: daniel-database-url
        property: DATABASE_URL
        
    # 2. Fetching the Read-Replica Database URL (For Reads)
    - secretKey: DATABASE_READ_URL
      remoteRef:
        key: daniel-database-url
        property: DATABASE_READ_URL
        
    # 3. Fetching the Redis Cluster URL
    - secretKey: REDIS_URL
      remoteRef:
        key: daniel-database-url
        property: REDIS_URL

    - secretKey: JWT_SECRET
      remoteRef:
        key: daniel-jwt-secret-driver-and-rider   # Points to your brand new AWS vault
        property: JWT_SECRET

    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: daniel-database-url
        property: REDIS_PASSWORD

    - secretKey: REDIS_HOST
      remoteRef:
        key: daniel-database-url
        property: REDIS_HOST

---
# 2. Email Service Secrets
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: email-secrets-fetcher
  namespace: rideshare-data
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: email-app-credentials # The new local container for your email pod
    creationPolicy: Owner
  data:
    - secretKey: AZURE_EMAIL_CONNECTION_STRING
      remoteRef:
        key: daniel-email-service
        property: AZURE_EMAIL_CONNECTION_STRING
        
    - secretKey: SENDER_EMAIL
      remoteRef:
        key: daniel-email-service
        property: SENDER_EMAIL

---
# 5. Google OAuth Credentials
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: google-oauth-fetcher
  namespace: rideshare-data
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: google-oauth-credentials 
    creationPolicy: Owner
  data:
    - secretKey: GOOGLE_CLIENT_SECRET
      remoteRef:
        key: daniel-google-oauth
        property: GOOGLE_CLIENT_SECRET    
    - secretKey: GOOGLE_CLIENT_ID
      remoteRef:
        key: daniel-google-oauth
        property: GOOGLE_CLIENT_ID
---
# 6. Frontend Secrets
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: frontend-secrets-fetcher
  namespace: rideshare-data
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: frontend-app-credentials 
    creationPolicy: Owner
  data:
    - secretKey: NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN
      remoteRef:
        key: daniel-mapbox
        property: NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN